### ISSUE TITLE
Map i18next language code to ICU locale

### ISSUE THREAD

**Issue by jamesots-tq** [i18next/i18next-icu#35]
## 🚀 Feature Proposal

I propose adding a way of mapping from the i18next language code to another code.

## Motivation

There may be a case where multiple sets of translations are required for the same language. For example, if a web app is deployed to multiple companies, each company may need their own company-specific set of translations, even though they're still using the same underlying language and locale.

At the moment I'm partially getting around this by using multiple custom region suffices, with the appropriate language code. e.g. en-ab, en-en, en-xy. This ensures that the correct plural forms are used. Unfortunately it ends up causing the wrong date formats to use, as they are based on the second part of the code.

It would be useful to be able to have resource packs named with arbitrary names, e.g. bobswidgets, sparklythings, default, and then be able to have a function which maps those names to correct locales. Or perhaps to use the modified codes as before (en-ab, en-en, en-xy) and map them to real locales (en-gb).

Although I particularly need this for i18next-icu, it may actually make sense to implement it in the main i18next package.

**Comment by jamuhl** [comment]
not 100% what you're requesting...

locales codes are defined like in ICU:

- `en` locale
- `en-US` locale + region
- `en-US-x-custom` locale + region + custom
- `zh-hant-CN` locale + script + region

**Comment by jamesots** [comment]
Thank you. I wasn't aware of the x-custom part, which gives me exactly what I need.

**Comment by kachkaev** [comment]
Maybe this is a somewhat unrelated question, but might be still worth asking in the same thread. Sorry if this is off-topic 🙏

Is it possible to map the rules of a completely different language id into a known one, e.g. English? I’d like to set up a new locale with id `zz-ZZ`, which would be a [pseudo version](https://github.com/MattBoatman/i18next-pseudo) of English.

When I go for `new Pseudo({ languageToPseudo: "en-ZZ" })`, the UI renders as expected, i.e. I see `[42 ααṗṗḽḛḛṡ]` instead of `42 apples`. However, each instance of an ICU string with plural produces this warning in the browser console:

```
i18next::pluralResolver: no plural rule found for: zz-ZZ 
```

Is there any way I can tell `i18next-icu` to treat `zz` exactly like `en` in terms of the pluralization rules?

**Comment by jamuhl** [comment]
@kachkaev hm...only option I could think of is adding some parseLngForICU function here: https://github.com/i18next/i18next-icu/blob/master/src/index.js#L66

what do you think? Doable? Practical? PR welcome

**Comment by kachkaev** [comment]
Thanks for your reply @jamuhl, the idea makes sense! I’ll submit a PR within a few weeks unless we decide to replace `zz-ZZ` with `en-ZZ` (or something like that). Being able to do so can let us specify several pseudo-locales (e.g. `en-ZZ` and `es-ZZ`) and won’t require any upstream changes. If something can be solved without widening APIs between systems, that’s better for everyone 🙂
